[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "openMTPK"
authors = [{name = "Akiel Aries", email = "akiel@akiel.org"}]
dynamic = ["v0.2", "Reusable Mathematics"]
